Responsive Next web clone
NtwaliHeritier/next-web-responsive pull request #1
Opened 2020-08-27 09:42 UTC by NtwaliHeritier

We cloned the next web page using: 
- grids to design the article section
- flexboxes to design the navbar
- floats to move an icon to the right in the footer
- media queries to make the webpage responsive on different devices
- fontawesome to include some icons in the web page.

2020-08-27 11:44 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

Hello :handshake: 

You did a very good job on this project. The design looks great, and I can see that you have great attention to detail :clap:  Your code is also clan and well structured :100: 

However, there are a few mistakes that we need to fix in order to move on:

- [ ] It seems that you did not change the layout of the page on the medium screen size. Kindly address that. Your clone should reflect the same items per columns and number of rows of the original.

:arrow_down: 

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91437812-d8bc6e00-e840-11ea-93b5-8c0dcc3d0736.png) | ![image](https://user-images.githubusercontent.com/61479648/91437987-10c3b100-e841-11ea-95c4-cf569195dbb8.png) |

- [ ] Check the inline comments for more.

#### You should be proud. The page already looks really great!

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-27 11:44 UTC, expjazz commented on index.css
> +    width: 100%;
- [ ] As the requirements in pathwright state, you should use the mobile-first approach, that means that the default is the small screen and no media queries are used for this size, next you should state the media queries for tablet @media screen and (min-width: 768px) and lastly the media queries for desktop @media screen and (min-width: 1024px). [You did desktop-first and established max-widths for your media queries]. Please correct this.

2020-08-27 11:44 UTC, expjazz commented on index.html
> +              <p class="second-p"><a href="#">Rachel Kaser</a> - 13hours ago</p>
#### Mobile Screen Size

- [ ] The author's name here is with the wrong styling.

- [ ] The image can be smaller

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91436463-8da15b80-e83e-11ea-9a39-8857b759d0f1.png)| ![image](https://user-images.githubusercontent.com/61479648/91436487-9b56e100-e83e-11ea-9574-ae4dbee1a3ad.png)  |

2020-08-27 11:44 UTC, expjazz commented on index.html
> +
#### Mobile Screen Size

- [ ] The layout of these links is different from the original

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91436662-ed980200-e83e-11ea-843d-965a5d249943.png) | ![image](https://user-images.githubusercontent.com/61479648/91436689-fb4d8780-e83e-11ea-86b0-32f5b4823509.png) |

2020-08-27 11:44 UTC, expjazz commented on index.html
> +            <div class="div2">
#### Mobile Screen Size

- [ ] The text on the right side of the image should not be centralized. Should be closer to the image.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91436839-47003100-e83f-11ea-8309-9713463c09da.png) |![image](https://user-images.githubusercontent.com/61479648/91436871-554e4d00-e83f-11ea-9cd4-afffa3a34532.png) |

2020-08-27 11:44 UTC, expjazz commented on index.html
> +            <h1>Latest news</h1>
- [ ] I know you did not worried about the content, but it is confusing to see the same title from a previous section again

2020-08-27 11:44 UTC, expjazz commented on index.html
> +            <img src="./images/suit.jpg" alt="image" />
#### Mobile Screen Size

- [ ] Here the layout is different from the original. Kindly address that.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91437213-e9b8af80-e83f-11ea-855c-0f1962054e32.png) | ![image](https://user-images.githubusercontent.com/61479648/91437235-f3421780-e83f-11ea-9ec5-04a61a631049.png) |

2020-08-27 11:44 UTC, expjazz commented on index.html
> +          <a href="#"><i class="fab fa-twitter fa-2x"></i></a>
#### Mobile Screen Size

- [ ] The bottom of the footer needs to be different

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91437361-28e70080-e840-11ea-8ec5-e5775b938d70.png)|![image](https://user-images.githubusercontent.com/61479648/91437388-31d7d200-e840-11ea-84d0-49fe1e4abe5d.png) |

2020-08-29 16:51 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2020-08-29 17:54 UTC, merged